# Generated by Django 6.0.3 on 2026-03-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_name',
            field=models.CharField(max_length=60),
        ),
    ]
