# Generated by Django 6.0.3 on 2026-03-24 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='api.address'),
            preserve_default=False,
        ),
    ]
