# Generated by Django 6.0.3 on 2026-03-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_number',
            field=models.CharField(max_length=10),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.menuitem'),
            preserve_default=False,
        ),
    ]
