# Generated by Django 6.0.3 on 2026-04-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_driverprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='special_instructions',
            field=models.TextField(null=True),
        ),
    ]
